# Original render.yaml (before changes)
services:
  - type: web
    name: cse340-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: cse340-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true

# Updated render.yaml (after changes)
services:
  - type: web
    name: cse340-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: cse340-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true